name: aml_real_deployment

description: execute an online endpoint for real time inference

inputs:
  SUBSCRIPTION_ID:
    description: "subscription id needed for deployment"
    required: true
  use_case_base_path:
    description: "the flow to be registered and deployed"
    required: true
  MODEL_VERSION:
    description: "flow version in registry to be deployed"
    required: true
  DEPLOY_ENVIRONMENT:
    description: "env stage e.g. dev, test, prod"
    required: true


runs:
  using: composite
  steps:
    - name: Provision AML Online Endpoint
      uses: ./.github/actions/execute_script
      with:
        step_name: "Provision AML Online Endpoint"
        script_parameter: |
          python -m llmops.common.deployment.provision_endpoint \
            --subscription_id ${{ inputs.SUBSCRIPTION_ID }} \
            --build_id ${{ github.run_id }} \
            --output_file "endpoint_principal.txt" \
            --env_name ${{ inputs.DEPLOY_ENVIRONMENT }} \
            --base_path ${{ inputs.use_case_base_path }}

    - name: Read system managed id information
      shell: bash
      run: |
        readarray arr <"endpoint_principal.txt"
        endpoint_principal=${arr[0]}
        echo $endpoint_principal
        echo "ENDPOINT_PRINCIPAL=${endpoint_principal}"  >> "$GITHUB_ENV"

    - name: Assign Azure resource permissions
      shell: bash
      run: |
        echo $KEY_VAULT_NAME
        echo $RESOURCE_GROUP_NAME
        echo $WORKSPACE_NAME

        az role assignment create --assignee $ENDPOINT_PRINCIPAL --role "AzureML Data Scientist" --scope "/subscriptions/${{ inputs.SUBSCRIPTION_ID }}/resourcegroups/$RESOURCE_GROUP_NAME/providers/Microsoft.MachineLearningServices/workspaces/$WORKSPACE_NAME"
        auth_type=$(az keyvault show -n $KEY_VAULT_NAME  -g $RESOURCE_GROUP_NAME --query "properties.enableRbacAuthorization")
        if [[ -z "$auth_type" ]]; then
            echo "assigning RBAC permission"
            az role assignment create --assignee $ENDPOINT_PRINCIPAL --role "Key Vault Reader" --scope "/subscriptions/${{ inputs.SUBSCRIPTION_ID }}/resourcegroups/$RESOURCE_GROUP_NAME/providers/Microsoft.KeyVault/vaults/$KEY_VAULT_NAME"
        else
            echo "assigning policy permission"
            az keyvault set-policy --name $KEY_VAULT_NAME --resource-group $RESOURCE_GROUP_NAME --object-id $ENDPOINT_PRINCIPAL --secret-permissions get list
        fi

    - name: Provision AML Online Deployment
      uses: ./.github/actions/execute_script
      with:
        step_name: "Provision AML Online Deployment"
        script_parameter: |
          python -m llmops.common.deployment.provision_deployment \
            --subscription_id ${{ inputs.SUBSCRIPTION_ID }} \
            --model_version ${{ inputs.MODEL_VERSION }} \
            --build_id ${{ github.run_id }} \
            --env_name ${{ inputs.DEPLOY_ENVIRONMENT }} \
            --base_path ${{ inputs.use_case_base_path }}

    - name: Test AML Deployment
      uses: ./.github/actions/execute_script
      with:
        step_name: "Test AML Deployment"
        script_parameter: |
          python -m llmops.common.deployment.test_model_on_aml \
            --subscription_id ${{ inputs.SUBSCRIPTION_ID }} \
            --env_name ${{ inputs.DEPLOY_ENVIRONMENT }} \
            --base_path ${{ inputs.use_case_base_path }}