name: named_entity_recognition_ci_dev_pipeline

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      use_case_base_path:
        type: string
        description: "The flow usecase to execute"
        required: true
        default: "named_entity_recognition"
      deployment_type:
        type: string
        description: "Determine type of deployment - aml, aks, docker, webapp"
        required: true
        default: "aks"
  push:
    branches:
      - main
      - development
    paths:
      - '.github/**'
      - 'llmops/**'
      - 'named_entity_recognition/**'

#=====================================
# Execute platform_ci_dev_workflow workflow for experiment, evaluation and deployment of flows
#=====================================
jobs:
  execute-platform-flow-ci:
    uses: ./.github/workflows/platform_ci_dev_workflow.yml
    with:
      env_name: ${{ inputs.env_name || 'dev'}}
      use_case_base_path: ${{ inputs.use_case_base_path || 'named_entity_recognition' }}
      deployment_type: ${{ inputs.deployment_type|| 'aks' }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      connection_details: ${{ secrets.COMMON_DEV_CONNECTIONS }}
      registry_details: ${{ secrets.DOCKER_IMAGE_REGISTRY }}